#cloud-config
autoinstall:
  version: 1

  locale: en_US.UTF-8

  keyboard:
    layout: us

  identity:
    hostname: k8s-node-02
    realname: dev
    username: dev
    password: ${{ secrets.UBUNTU_PASSWORD }}

  ssh:
    install-server: true
    # allows password login
    allow-pw: true
    authorized-keys:
      # does not install an SSH public key
      []
      # to enable - REPLACE_WITH_YOUR_SSH_PUBLIC_KEY

  network:
    version: 2
    ethernets:
      eno1:
        dhcp4: true
        dhcp6: false

  source:
    id: ubuntu-server
    search_drivers: false

  packages: []

  updates: security