#cloud-config

autoinstall:  # starts the autoinstall configuration
  version: 1  # autoinstall schema version

  locale: en_US.UTF-8  # system language

  keyboard:  # configures the keyboard
    layout: us  # us keyboard layout

  identity:  # defines identity information
    hostname: ${HOSTNAME}  # replace it with a hostname
    realname: ${REALNAME}  # replace it with the admin name
    username: ${USERNAME}  # replace it with the username
    password: '${PASSWORD_HASH}'  # replace it with a password hash

  ssh:  # configures SSH access to the installed server
    install-server: true  # installs and enables the OpenSSH server
    allow-pw: true  # allows users to authenticate through SSH with a password
    authorized-keys: []  # no SSH public keys

  source:  # selects the Ubuntu source
    id: ubuntu-server  # installs the Ubuntu Server
    search_drivers: false  # no search for third-party drivers

  packages: []  # no additional packages

  updates: security  # installs available security updates
